# Generated by Django 5.2.4 on 2025-08-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='address_line1',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='pincode',
            field=models.CharField(default='000000', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
